# run simply with `docker-compose build --pull --no-cache && docker-compose --compatibility up -d`

version: "3"

services:
  plex:
    build:
        context: .
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="America/Los_Angeles"    # FIRST TIME ONLY
      - PLEX_CLAIM="${PLEX_CLAIM_TOKEN}"   # FIRST TIME ONLY https://www.plex.tv/claim/
      - ADVERTISE_IP="http://${PLEX_IP_ADDRESS}:32400/" # FIRST TIME ONLY
    volumes:
      - /var/b-media/plex/database:/config
      - /var/b-media/plex/transcode/temp:/transcode
      - /var/b-media/plex/media:/data
    hostname: "plex-container"
    restart: always

networks:
  default:
    external:
      name: b-server
