# run simply with `docker-compose build --pull --no-cache`
version: "3"

services:
  qbittorrent:
    image: qbittorrent
    build:
      context: .
    ports:
      - 8080:8080/tcp
      - 9000:9000
    volumes:
      - /var/qbittorrent/config:/root/.config/qBittorrent
      - /var/qbittorrent/data:/root/.local/share/qBittorrent/
      #! UPDATE THIS FOR CURRENT SYSTEM
      - /home/bevrist/systems/containers/b-media/qbittorrent/aaa:/mnt
    hostname: "share-qb"
    restart: unless-stopped
