---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deployment-nfs-test
spec:
  accessModes:
    - ReadWriteMany  # In this example, multiple Pods consume the same PVC.
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nfs-test
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment-nfs-test
  template:
    metadata:
      name: deployment-nfs-test
      labels:
        name: deployment-nfs-test
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: deployment-nfs-test
          image: debian
          command:
            - "/bin/bash"
            - "-c"
            - while true; do echo $(hostname) $(date) >> /mnt/nfs/outfile; echo ---; cat /mnt/nfs/outfile; sleep 5; done
          volumeMounts:
            - name: nfs
              mountPath: "/mnt/nfs"
              readOnly: false
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: pvc-deployment-nfs-test
