version: "2"

services:
  minecraft-bedrock:
    build:
      context: .
    ports:
      - "19132:19132/udp"
    volumes:
      - ${PWD}/data:/app
      - ${PWD}/config:/config
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - UPDATE=${UPDATE}
