# Docker compose builds and runs multiple docker containers
# run simply with `docker-compose up --build`

# be sure to docker build github-runner[1-3] first

version: "3"

services:
  github-runner1:
    image: github-runner1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  github-runner2:
    image: github-runner2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  github-runner3:
    image: github-runner3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
