
# ssh container (depends on website pvc)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-deployment
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
      - name: ssh
        image: 192.168.86.7:5000/ssh-image # FIXME: update IP
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 5m
            memory: 100Mi
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 22
        ports:
        - containerPort: 22
          protocol: TCP
        volumeMounts:
        - name: website-share-volume
          mountPath: /www/brettevrist.net/share
        - name: website-ios-volume
          mountPath: /www/brettevrist.net/ios
      volumes:
      - name: website-share-volume
        persistentVolumeClaim:
          claimName: website-share-pvc
      - name: website-ios-volume
        persistentVolumeClaim:
          claimName: website-ios-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  namespace: website
spec:
  selector:
    app: ssh
  ports:
    - name: ssh-port
      port: 2222
      targetPort: 22
  type: LoadBalancer
