# enable homebrew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

macchina -t Bretts_Theme

export HOMEBREW_NO_ENV_HINTS=1

### Aliases
# alias ls="ls -G"
# alias la="ls -lahG"
# alias ll="ls -lhG"
alias ls="lsd"
alias la="lsd -la"
alias ll="lsd -l"
alias k="kubectl"
alias d="docker"

### Zsh Completions
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

### zsh prompt customizations
autoload -Uz compinit

# run compinit once every 24 hours
if [ ! -f ~/.zcompdump ]; then touch -t 201001010000 ~/.zcompdump; fi
if [ "$(( $(date +%s) - $(date -r ~/.zcompdump +%s) ))" -gt 86400 ]; then
  compinit
  touch ~/.zcompdump
else
  compinit -C
fi

# auto cd
setopt autocd
# case insensitive tab completion
# zstyle ":completion:*" matcher-list "m:{a-z}={A-Z}"
zstyle ":completion:*" matcher-list "" "+m:{a-zA-Z}={A-Za-z}" "+r:|[._-]=* r:|=*" "+l:|=* r:|=*"
# up arrow down arrow history load
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down
# option+arrow shell navigation
bindkey "^[^[[C" forward-word # Right
bindkey "^[^[[D" backward-word # Left

# zsh-syntax-highlighting
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

# zsh-autosuggestions
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source <(kubectl completion zsh)
compdef k='kubectl'  #zsh-completion for `k` alias

# center justify text function
center () {
  if [ -z "$2" ]; then 2='#'; fi
  if [ -z "$3" ]; then 3=40; fi
  echo $(perl -e "print '$2' x $3") $1 $(perl -e "print '$2' x $3")
}

eval "$(starship init zsh)"