version: "2"

services:
  minecraft-floodgate:
    build:
      context: .
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - papermc-floodgate:/paper
    restart: on-failure
    stdin_open: true
    tty: true

volumes:
  papermc-floodgate:
