# https://starship.rs/config
add_newline = false
command_timeout = 1000
scan_timeout = 50
continuation_prompt = ">>"

[character]
success_symbol = "[>](bold white)"
error_symbol = "[>](bold red)"

[line_break]
disabled = true

[status]
disabled = false
format = "[$status]($style)"

[cmd_duration]
format = "[took $duration]($style) "
#show_notifications = true
#min_time_to_notify = 5000

[directory]
truncate_to_repo = false
style = "white"
read_only = " "
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "[\\([$symbol$branch](green)\\)](purple)"
only_attached = true
[git_commit]
format= "[\\([$hash](green)\\)](purple) "
[git_status]
format = "([\\[$all_status$ahead_behind\\]](purple)) "
stashed = "[$](bold orange)"
renamed = "[»](bold blue)"
deleted = "[✘](bold red)"
staged = "[+](bold green)"
conflicted = "[✖](red)"
modified = "[●](bold blue)"
behind = "[⇣$count](bold white)"
ahead = "[⇡$count](bold white)"
diverged = "[⇕$count](bold white)"
untracked = "[?](bold yellow)"

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[hostname]
disabled = true

[username]
format = "[$user]($style) "

### Symbol config ###
[aws]
symbol = "  "
format = 'via [$symbol]($style)'
[buf]
symbol = " "
format = "via [$symbol]($style)"
[c]
symbol = " "
format = 'via [$symbol]($style)'
[cmake]
format = "via [$symbol]($style)"
[conda]
symbol = " "
format = 'via [$symbol]($style)'
[crystal]
format = "via [$symbol]($style)"
[dart]
symbol = " "
format = "via [$symbol]($style)"
[deno]
format = "via [$symbol]($style)"
[docker_context]
symbol = " "
format = 'via [$symbol]($style)'
[dotnet]
symbol = " "
format = "[$symbol(🎯 $tfm )]($style)"
[elixir]
symbol = " "
format = 'via [$symbol]($style)'
[elm]
symbol = " "
format = 'via [$symbol]($style)'
[erlang]
symbol = " "
format = 'via [$symbol]($style)'
[golang]
symbol = " "
format = 'via [$symbol]($style)'
[haskell]
symbol = " "
format = 'via [$symbol]($style)'
[helm]
symbol = "⎈ "
format = 'via [$symbol]($style)'
[java]
symbol = " "
format = 'via [$symbol]($style)'
[julia]
symbol = " "
format = 'via [$symbol]($style)'
[kotlin]
format = 'via [$symbol]($style)'
[lua]
symbol = " "
format = 'via [$symbol]($style)'
[nim]
symbol = " "
format = 'via [$symbol]($style)'
[nix_shell]
symbol = " "
[nodejs]
symbol = " "
format = 'via [$symbol]($style)'
[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'
[package]
symbol = " "
format = 'via [$symbol]($style)'
[perl]
symbol = " "
format = 'via [$symbol]($style)'
[php]
symbol = " "
format = 'via [$symbol]($style)'
[pulumi]
format = 'via [$symbol$stack]($style)'
[purescript]
format = 'via [$symbol]($style)'
[python]
symbol = " "
format = 'via [$symbol]($style)'
[spack]
symbol = "🅢 "
format = 'via [$symbol]($style)'
[red]
format = 'via [$symbol]($style)'
[rlang]
format = 'via [$symbol]($style)'
[ruby]
symbol = " "
format = 'via [$symbol]($style)'
[rust]
symbol = " "
format = 'via [$symbol]($style)'
[scala]
symbol = " "
format = 'via [$symbol]($style)'
[swift]
symbol = "ﯣ "
format = 'via [$symbol]($style)'
[vagrant]
format = 'via [$symbol]($style)'
[vlang]
format = 'via [$symbol]($style)'
[zig]
format = 'via [$symbol]($style)'
