" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible


set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
"set visualbell                  "No sounds
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set autoread                    "Reload files changed outside vim
set syntax                      "Enable syntax highlighting
set incsearch                   "Jump to first match when searching
set smartcase                   "Find/Replace handle letter case intellegently

" ================ Scrolling ========================
set scrolloff=4         "Start scrolling when we're 4 lines away from margins
set sidescrolloff=5
set sidescroll=1

" ================ Indentation ======================
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

" ================ Turn Off Swap Files ==============
set noswapfile
set nobackup
set nowb

