# run simply with `docker-compose build --pull --no-cache && docker-compose up -d`
# TODO UPDATE CF_* ENV VARS
# CF_TOKEN needs to be a cloudflare token with `Zone-DNS-Edit` and `Zone-Zone-Read` permissions

version: "3"

services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - $PWD/ddclient.conf:/config/ddclient.conf
    restart: unless-stopped
