---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brettevrist-net-cert-request
  namespace: website
spec:
  secretName: brettevrist-net-cert-secret
  commonName: brettevrist.net
  dnsNames:
    - "brettevrist.net"
    - "*.brettevrist.net"
    - "*.kube.brettevrist.net"
    - "brettevrist.com"
    - "evri.st"
    - "mealie.brettevrist.net"
    - "mealie.evri.st"
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
