# Helium

hide_ascii      = false
spacing         = 1
padding         = 0
separator       = "=>"
key_color       = "Blue"
separator_color = "Yellow"

[palette]
type            = "Light"
glyph           = " ● "
visible         = true

[bar]
glyph           = "o"
symbol_open     = "("
symbol_close    = ")"
hide_delimiters = false
visible         = false

[box]
title           = " Brett's Theme "
border          = "rounded"
visible         = false

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "Red"
path 			      = "~/.config/macchina/themes/debian_logo.txt"

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
local_ip        = "IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
