# run simply with `docker-compose build --pull --no-cache && docker-compose --compatibility up -d`

version: "3"

services:
  b-web:
    build:
      context: ./b-web-nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
        - /var/b-web/share:/var/www/share
        - /var/b-web/ios:/var/www/ios
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 0.5
    #       memory: 50M

  certbot:
    build:
      context: ./certbot
    volumes:
      - /var/b-web/letsencrypt:/etc/letsencrypt

  # coredns:
  #   image: coredns/coredns
  #   ports: 53:53/udp
  #   command: "-conf /root/Corefile"
  #   restart: always

  nginx-proxy:
    build:
      context: ./nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/b-web/letsencrypt:/etc/letsencrypt
    restart: always

  ssh:
    build:
      context: ./ssh
    ports:
      - "2220:22"
    hostname: "ssh-container"
    volumes:
      - /var/b-web/share:/var/b-web/share
      - /var/b-web/addmovie:/var/b-web/addmovie
      - /var/b-web/addTV:/var/b-web/addTV
      - /var/b-web/ios:/var/b-web/ios
    restart: always

networks:
  default:
    external:
      name: b-server
