# /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
# export IP="192.168.1.22" ; cat containerd-config.toml | envsubst
# push images to "$IP:5000/image-name"

{{ template "base" . }}

[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."$IP:5000"]
      endpoint = ["http://$IP:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."$IP:5000".tls]
      insecure_skip_verify = true
