version: "2"

services:
  satisfactory:
    build:
      context: .
    ports:
      - "7777/udp"
      - "15000/udp"
      - "15777/udp"
    volumes:
      - ${PWD}/data:/app
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - UPDATE=${UPDATE}
