# run simply with `docker-compose build --pull --no-cache`
version: "3"

services:
  samba:
    build:
      context: .
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    volumes:
      - "/mnt/6TB-5400RPM/BACKUP/Games Archive:/games-archive:ro"
    hostname: "samba"
    restart: unless-stopped
