---
# Deployment for website
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website  # must match spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: website  # must match spec.selector.matchLabels
    spec:
      containers:
      - name: website
        image: local-registry:5000/website-image
        imagePullPolicy: Always
        ports:
        - name: main-port
          containerPort: 8080
        - name: play-port
          containerPort: 8081
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
        readinessProbe:
          httpGet:
            port: 8080
        livenessProbe:
           httpGet:
            port: 8080
        volumeMounts:
        - name: website-share-volume
          mountPath: /www/brettevrist.net/share
          readOnly: true
        - name: website-ios-volume
          mountPath: /www/brettevrist.net/ios
          readOnly: true
      volumes:
      - name: website-share-volume
        persistentVolumeClaim:
          claimName: website-share-pvc
      - name: website-ios-volume
        persistentVolumeClaim:
          claimName: website-ios-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: website
spec:
  selector:
    app: website
  ports:
    - name: main-port
      protocol: TCP
      port: 8080
    - name: play-port
      protocol: TCP
      port: 8081
