---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-share-pvc
  namespace: website
spec:
  accessModes:
    - ReadWriteOnce # only needs to be on one node
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-ios-pvc
  namespace: website
spec:
  accessModes:
    - ReadWriteOnce # only needs to be on one node
  resources:
    requests:
      storage: 5Gi
