# skaffold build --cache-artifacts=false
# skaffold run --cache-artifacts=false
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: website-skaffold
build:
  cluster: {}
  artifacts:
    - image: local-registry:5000/website-image
      kaniko:
        insecure: true
        useNewRun: true
        cache:
          cacheCopyLayers: true
manifests:
  rawYaml:
    - kube/*.yaml
