apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: website-skaffold
build:
  artifacts:
  - image: website-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kube/website.yaml
