# docker-compose up -d
version: "3.7"

services:
  svnedge:
    image: svnedge/app:latest
    restart: unless-stopped
    ports:
      - "18080:18080"
      - "3343:3343"
    environment:
      SET_PERMS: "false"
    volumes:
      - data:/home/svnedge/csvn/data

volumes:
  data:

# for admin access, navigate directly to port 3343
# backup dumps are stored in the data volume at `/home/svnedge/csvn/data/dumps`
