# Default certificate for traefik to use in all namespaces
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: traefik-default-cert
  namespace: website
spec:
  defaultCertificate:
    secretName: brettevrist-net-cert-secret
